### ISSUE TITLE
Can't run ReaStreamReceiverStandalone.exe

### ISSUE THREAD

**Issue by AtmanActive** [JessyJP/ReaStream-Standalone-Application#1]
Greetings!
And thank you for this interesting software.

Unfortunately, I was unable to run ReaStreamReceiverStandalone.exe that I've downloaded from your releases page because of the following error:

![2022-06-03_11-53-15](https://user-images.githubusercontent.com/7526717/171840680-510bcc9b-a44d-4203-860f-dfb311499258.png)

I will now try to find mclmcrrt9_12.dll somewhere and add it to the folder in hopes I can make it work.
I just wanted to let you know.

Thanks.

Cheers!

**Comment by JessyJP** [comment]
Hello, thank you for your interest in this project. 
The feedback is much appreciated. 

The issue is related to MATLAB's Runtime environment. 
Have you tried the other folder containing the MyAppInstaller_web.exe?
The executable assumes you have the MATLAB runtime environment preinstalled, which happens when either:
1) MATLAB installed.  
2) The Matlab runtime environment is installed from the Mathworks website manually. - https://www.mathworks.com/products/compiler/matlab-runtime.html
3) A previously installed app downloaded and installed the runtime environment from the web via a redistributable package. - which is what was supposed to happen here.

I will repack the release with the runtime included rather than relying on the internet install.
----------------------------
Sidenote: To test the app set up something like that in reaper or another DAW or VST host.

![image](https://user-images.githubusercontent.com/49342341/173029604-b5fae6ba-bf11-4383-ba6c-325caab7a804.png)
![image](https://user-images.githubusercontent.com/49342341/173029672-b388f9f0-f63f-4205-9daa-28089b0f93f1.png)
![image](https://user-images.githubusercontent.com/49342341/173031225-c81f2019-9360-41a1-a199-5edbfce9f217.png)

The app is more for testing purposes because you can effectively do the same thing with a VST host with the ReaStream plugin on the client-side.
The power in this project is actually the code itself as it allows packet by packet, sample by sample control.
